export interface Contrato {
  idContrato: string;
  statusContrato: "Ativo" | "Encerrado" | "Suspenso" | string;
  numeroContrato: number;
  anoContrato: number;
  processoSEI: string;
  objeto: string;
  categoriaContrato: string;
  tipoContratacao: string;
  numeroLicitacao: number;
  fornecedor: string;
  cnpjFornecedor: string;
  inicioVigencia: string;
  fimVigencia: string;
  possibilidadeProrrogacao: boolean | null;
  necessitaNovaContratacao: boolean | null;
  valorInicialContrato: number;
  valorAtualizado: number;
  recorrenciaContratual: "mensal" | "sobDemanda" | "unica" | string;
  valorMensal: number | null;
  saldoContrato: number;
  possuiReajuste: boolean;
  indiceReajuste: string | null;
  gestorContrato: string;
  fiscalContrato: string;
  riscoDescontinuidade: "Alto" | "Médio" | "Baixo" | string;
  servicoEssencial: boolean;
}

export const contratosData: Contrato[] = [
  {
    "idContrato": "202201",
    "statusContrato": "Ativo",
    "numeroContrato": 1,
    "anoContrato": 2022,
    "processoSEI": "00.000.0000.00000",
    "objeto": "Contrato",
    "categoriaContrato": "Juridicos",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": 11,
    "fornecedor": "AAAA AAAAAAAA AAAA",
    "cnpjFornecedor": "00.000.000/0000-01",
    "inicioVigencia": "2022-01-01",
    "fimVigencia": "2027-01-01",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 10000.0,
    "valorAtualizado": 50000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 833.3333333,
    "saldoContrato": 4166.666667,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "AAAA",
    "fiscalContrato": "EEEE",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "202302",
    "statusContrato": "Ativo",
    "numeroContrato": 2,
    "anoContrato": 2023,
    "processoSEI": "00.000.0000.00001",
    "objeto": "",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": 22,
    "fornecedor": "BBBB BBBBBBBB BBBB",
    "cnpjFornecedor": "00.000.000/0000-02",
    "inicioVigencia": "2023-02-01",
    "fimVigencia": "2027-02-01",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 11000.0,
    "valorAtualizado": 44000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 916.6666667,
    "saldoContrato": 5500.0,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "AAAA",
    "fiscalContrato": "DDDD",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "202403",
    "statusContrato": "Ativo",
    "numeroContrato": 3,
    "anoContrato": 2024,
    "processoSEI": "00.000.0000.00002",
    "objeto": "",
    "categoriaContrato": "Serviço",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": 33,
    "fornecedor": "CCCC CCCCCCCC CCCC",
    "cnpjFornecedor": "00.000.000/0000-03",
    "inicioVigencia": "2024-03-01",
    "fimVigencia": "2027-03-01",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 12000.0,
    "valorAtualizado": 36000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 1000.0,
    "saldoContrato": 7000.0,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "BBBB",
    "fiscalContrato": "CCCC",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "202504",
    "statusContrato": "Ativo",
    "numeroContrato": 4,
    "anoContrato": 2025,
    "processoSEI": "00.000.0000.00003",
    "objeto": "",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": 44,
    "fornecedor": "DDDD DDDDDDDD DDDD",
    "cnpjFornecedor": "00.000.000/0000-04",
    "inicioVigencia": "2025-04-01",
    "fimVigencia": "2027-04-01",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 13000.0,
    "valorAtualizado": 26000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 1083.333333,
    "saldoContrato": 8666.666667,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "CCCC",
    "fiscalContrato": "FFFF",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "202605",
    "statusContrato": "Ativo",
    "numeroContrato": 5,
    "anoContrato": 2026,
    "processoSEI": "00.000.0000.00004",
    "objeto": "",
    "categoriaContrato": "Materiais Permanente",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": 55,
    "fornecedor": "EEEE EEEEEEEE EEEE",
    "cnpjFornecedor": "00.000.000/0000-05",
    "inicioVigencia": "2026-06-01",
    "fimVigencia": "2027-06-01",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": null,
    "valorInicialContrato": 14000.0,
    "valorAtualizado": 14000.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "saldoContrato": 7000.0,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "CCCC",
    "fiscalContrato": "GGGG",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "202206",
    "statusContrato": "Ativo",
    "numeroContrato": 6,
    "anoContrato": 2022,
    "processoSEI": "00.000.0000.00005",
    "objeto": "",
    "categoriaContrato": "Materiais de Consumo",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": 66,
    "fornecedor": "FFFF FFFFFFFF FFFF",
    "cnpjFornecedor": "00.000.000/0000-06",
    "inicioVigencia": "2022-07-01",
    "fimVigencia": "2027-07-01",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 15000.0,
    "valorAtualizado": 75000.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "saldoContrato": 5000.0,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "CCCC",
    "fiscalContrato": "GGGG",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "202307",
    "statusContrato": "Ativo",
    "numeroContrato": 7,
    "anoContrato": 2023,
    "processoSEI": "00.000.0000.00006",
    "objeto": "",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": 77,
    "fornecedor": "GGGG GGGGGGGG GGGG",
    "cnpjFornecedor": "00.000.000/0000-07",
    "inicioVigencia": "2023-08-01",
    "fimVigencia": "2026-08-01",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 16000.0,
    "valorAtualizado": 48000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 1333.333333,
    "saldoContrato": 1333.333333,
    "possuiReajuste": true,
    "indiceReajuste": "IGPM",
    "gestorContrato": "DDDD",
    "fiscalContrato": "GGGG",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": true
  },
  {
    "idContrato": "202408",
    "statusContrato": "Ativo",
    "numeroContrato": 8,
    "anoContrato": 2024,
    "processoSEI": "00.000.0000.00007",
    "objeto": "",
    "categoriaContrato": "Atuariais",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": 88,
    "fornecedor": "HHHH HHHHHHHH HHHH",
    "cnpjFornecedor": "00.000.000/0000-08",
    "inicioVigencia": "2024-09-01",
    "fimVigencia": "2026-09-01",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 17000.0,
    "valorAtualizado": 34000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 1416.666667,
    "saldoContrato": 2833.333333,
    "possuiReajuste": true,
    "indiceReajuste": "IGPM",
    "gestorContrato": "EEEE",
    "fiscalContrato": "HHHH",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": true
  },
  {
    "idContrato": "202509",
    "statusContrato": "Encerrado",
    "numeroContrato": 9,
    "anoContrato": 2025,
    "processoSEI": "00.000.0000.00008",
    "objeto": "",
    "categoriaContrato": "Juridicos",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": 99,
    "fornecedor": "IIII IIIIIIII IIII",
    "cnpjFornecedor": "00.000.000/0000-09",
    "inicioVigencia": "2025-10-01",
    "fimVigencia": "2026-04-01",
    "possibilidadeProrrogacao": null,
    "necessitaNovaContratacao": null,
    "valorInicialContrato": 18000.0,
    "valorAtualizado": 18000.0,
    "recorrenciaContratual": "mensal",
    "valorMensal": 1500.0,
    "saldoContrato": 0.0,
    "possuiReajuste": true,
    "indiceReajuste": "IGPM",
    "gestorContrato": "EEEE",
    "fiscalContrato": "HHHH",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "202610",
    "statusContrato": "Suspenso",
    "numeroContrato": 10,
    "anoContrato": 2026,
    "processoSEI": "00.000.0000.00009",
    "objeto": "",
    "categoriaContrato": "Seguros",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": 100,
    "fornecedor": "JJJJ JJJJJJJJ JJJJ",
    "cnpjFornecedor": "00.000.000/0000-10",
    "inicioVigencia": "2026-11-01",
    "fimVigencia": "2027-11-01",
    "possibilidadeProrrogacao": null,
    "necessitaNovaContratacao": null,
    "valorInicialContrato": 19000.0,
    "valorAtualizado": 19000.0,
    "recorrenciaContratual": "unica",
    "valorMensal": null,
    "saldoContrato": 0.0,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "EEEE",
    "fiscalContrato": "AAAA",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  }
];
