export interface Contrato {
  idContrato: string;
  statusContrato: "Ativo" | "Encerrado" | "Suspenso" | string;
  numeroContrato: number;
  anoContrato: number;
  processoSEI: string | null;
  objeto: string;
  categoriaContrato: string;
  tipoContratacao: string;
  numeroLicitacao: string | number;
  fornecedor: string;
  cnpjFornecedor: string;
  inicioVigencia: string;
  fimVigencia: string;
  possibilidadeProrrogacao: boolean | null;
  necessitaNovaContratacao: boolean | null;
  valorInicialContrato: number;
  valorAtualizado: number | null;
  recorrenciaContratual: string;
  valorMensal: number | null;
  possuiReajuste: boolean;
  indiceReajuste: string | null;
  gestorContrato: string;
  fiscalContrato: string;
  riscoDescontinuidade: "Alto" | "Médio" | "Baixo" | string;
  servicoEssencial: boolean;
}

export const contratosData: Contrato[] = [
  {
    "idContrato": "C022026",
    "statusContrato": "Ativo",
    "numeroContrato": 2,
    "anoContrato": 2026,
    "processoSEI": "03.31.00000380/2026.70",
    "objeto": "Contratação de empresa especializada para prestação de serviços técnicos de assessoria ao Regime Próprio de Previdência Social – RPPS da Maringá Previdência, visando ao fortalecimento da governança institucional, ao aperfeiçoamento da gestão previdenciária e administrativa e à implementação de ações estratégicas voltadas à obtenção e manutenção da certificação institucional no âmbito do Programa de Certificação Institucional e Modernização da Gestão dos Regimes Próprios de Previdência Social da União, dos Estados, do Distrito Federal e dos Municípios – Pró-Gestão RPPS.",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "7/2026",
    "fornecedor": "ABCPREV GESTÃO E FORMAÇÃO PREVIDENCIÁRIA LTDA – EPP",
    "cnpjFornecedor": "16.778.036/0001-30",
    "inicioVigencia": "2026-05-26",
    "fimVigencia": "2027-05-26",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 120000.0,
    "valorAtualizado": 120000.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "José",
    "fiscalContrato": "Raphael",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C032022",
    "statusContrato": "Encerrado",
    "numeroContrato": 3,
    "anoContrato": 2022,
    "processoSEI": "03.31.00000116/2022.32",
    "objeto": "Contratação de empresa especializada para prestação dos serviços continuados relativos à educação previdenciária no âmbito da Maringá Previdência",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "2/2022",
    "fornecedor": "ABCPREV GESTÃO E FORMAÇÃO PREVIDENCIÁRIA LTDA – EPP",
    "cnpjFornecedor": "16.778.036/0001-30",
    "inicioVigencia": "2022-08-01",
    "fimVigencia": "2023-07-31",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 46800.0,
    "valorAtualizado": 46800.0,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 3900.0,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C082023",
    "statusContrato": "Encerrado",
    "numeroContrato": 8,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000672/2023.52",
    "objeto": "Contratação de empresa especializada para prestação dos serviços continuados relativos à educação previdenciária no âmbito da Maringá Previdência.",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "2/2023",
    "fornecedor": "ABCPREV GESTÃO E FORMAÇÃO PREVIDENCIÁRIA LTDA – EPP",
    "cnpjFornecedor": "16.778.036/0001-30",
    "inicioVigencia": "2023-08-23",
    "fimVigencia": "2024-08-22",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 47100.0,
    "valorAtualizado": 47100.0,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 3925.0,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C022021",
    "statusContrato": "Encerrado",
    "numeroContrato": 2,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Prestação de serviços de informática compreendendo os serviços de fornecimento de locação de Software de Gestão Previdenciária para RPPS - Regime Próprio de Previdência Social, incluindo implantação, migração de dados, treinamento de usuários e manutenção mensal bem como serviço especializado de informática para elaboração de arquivos para migração no Sistema de Informações Gerenciais – SIG/RPPS",
    "categoriaContrato": "Atuarial",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "11/2021",
    "fornecedor": "ACTUARY SERVIÇOS DE INFORMÁTICA LTDA – ME",
    "cnpjFornecedor": "08.211.721/0001-52 ",
    "inicioVigencia": "2021-03-07",
    "fimVigencia": "2025-03-06",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 222000.0,
    "valorAtualizado": 985061.36,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 22052.73,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C012025",
    "statusContrato": "Ativo",
    "numeroContrato": 1,
    "anoContrato": 2025,
    "processoSEI": "03.31.00001489/2024.09",
    "objeto": "Contratação de empresa especializada para locação de software com tecnologia WEB, para gerenciamento dos sistemas de gestão do Regime Próprio de Previdência Social – RPPS, incluindo a sua instalação, migração de todos os dados existentes, treinamento de usuários, bem como serviços de manutenção, suporte, hospedagem e atualização.",
    "categoriaContrato": "Software",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "1/2025",
    "fornecedor": "ACTUARY SERVIÇOS DE INFORMÁTICA LTDA – ME",
    "cnpjFornecedor": "08.211.721/0001-52",
    "inicioVigencia": "2025-03-07",
    "fimVigencia": "2027-03-06",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 312000.0,
    "valorAtualizado": 637425.6,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 27118.8,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "José",
    "fiscalContrato": "Raphael",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C012026",
    "statusContrato": "Ativo",
    "numeroContrato": 1,
    "anoContrato": 2026,
    "processoSEI": "01.22.00069232/2025.93",
    "objeto": "Contratação de empresa para prestação de serviços de assistência à saúde dos servidores públicos efetivos ativos e seus dependentes da Prefeitura Municipal de Maringá, IPPLAM, AMR, IAM, Maringá Previdência e Câmara Municipal. O valor máximo estimado para a licitação é de R$ 44.521.920,00 para um total de até 36.000 vidas mensal, com o valor estimado de R$ 103,06 por vida e vigência de 12 meses, conforme contrato de Prestação de Serviço à ser firmado.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "144/2025",
    "fornecedor": "ASSOCIAÇÃO BENEFICENTE BOM SAMARITANO",
    "cnpjFornecedor": "04.792.670/0001-49 ",
    "inicioVigencia": "2026-02-01",
    "fimVigencia": "2027-01-31",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 8664460.32,
    "valorAtualizado": 8664460.32,
    "recorrenciaContratual": "Mensal",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "Edimar",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C052021",
    "statusContrato": "Encerrado",
    "numeroContrato": 5,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Prestação de serviços de limpeza e polimento dos veículos oficiais: VOLKSWAGEN VOYAGE, ano/mod 2009/2010, PLACA ARW 0165 e NISSAN SENTRA 2.0 S, ano/mod 2018/2019, PLACA BCF – 3568.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "3/2021",
    "fornecedor": "CARLOS ALBERTO CORREIA",
    "cnpjFornecedor": "13.802.584/0001-02",
    "inicioVigencia": "2021-06-24",
    "fimVigencia": "2022-06-23",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 2316.0,
    "valorAtualizado": 2316.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": false
  },
  {
    "idContrato": "C102021",
    "statusContrato": "Encerrado",
    "numeroContrato": 10,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Contratação de empresa jurídica especializada para prestar serviços de assessoria em perícias médicas dos segurados da Maringá Previdência.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "3/2021",
    "fornecedor": "CENTRO MÉDICO TERRA RICA",
    "cnpjFornecedor": "11.216.255/0001-02 ",
    "inicioVigencia": "2021-11-05",
    "fimVigencia": "2023-11-04",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 69600.0,
    "valorAtualizado": 143696.16,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 5800.0,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Maria Silvana",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C122021",
    "statusContrato": "Ativo",
    "numeroContrato": 12,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Cessão onerosa de uso de terreno e instalações próprias da Maringá Previdência, para exploração dos serviços de estacionamento rotativo.",
    "categoriaContrato": "Locação",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "4/2021",
    "fornecedor": "CITY PARKING ESTACIONAMENTO LTDA – ME",
    "cnpjFornecedor": "22.725.976/0001-64",
    "inicioVigencia": "2021-12-01",
    "fimVigencia": "2026-11-30",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 42060.0,
    "valorAtualizado": 42060.0,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 3944.85,
    "possuiReajuste": true,
    "indiceReajuste": "IGPM",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": true
  },
  {
    "idContrato": "C082022",
    "statusContrato": "Ativo",
    "numeroContrato": 8,
    "anoContrato": 2022,
    "processoSEI": "03.31.00000258/2022.78",
    "objeto": "Contratação de Cessão Não Onerosa de Software cujo objeto é a cessão do direito de uso, compreendendo serviços de suporte técnico operacional e manutenção de software digital de gerenciamento e controle de margem consignável e gestão de consignações facultativas em folha de pagamento, denominado Consignet (“SISTEMA”), de propriedade da CONSIGNET.",
    "categoriaContrato": "Software",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "8/2022",
    "fornecedor": "CONSIGNET SISTEMAS LTDA",
    "cnpjFornecedor": "23.112.748/0001-81",
    "inicioVigencia": "2022-11-25",
    "fimVigencia": "2027-12-24",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 0.01,
    "valorAtualizado": 0.01,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C052025",
    "statusContrato": "Ativo",
    "numeroContrato": 5,
    "anoContrato": 2025,
    "processoSEI": "03.31.00000342/2025.32",
    "objeto": "CONTRATAÇÃO DE PESSOA JURÍDICA ESPECIALIZADA PARA OPERACIONALIZAÇÃO DO EMPRÉSTIMO CONSIGNADO COM FORNECIMENTO DE SOFTWARE DE GESTÃO DE EMPRÉSTIMOS EM TOTAL CONFORMIDADE COM A LGPD, INCLUINDO CONTRATAÇÃO DE SEGURO PRESTAMISTA E SERVIÇOS ESPECIALIZADOS DE ATUÁRIA, ECONOMIA, DIREITO E ASSESSORIA DE INVESTIMENTO PARA EXECUÇÃO E CONTROLE DO OBJETO, DE ACORDO COM AS LEGISLAÇÕES VIGENTES.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "2/2025",
    "fornecedor": "CONSIGNET SISTEMAS LTDA",
    "cnpjFornecedor": "23.112.748/0001-81",
    "inicioVigencia": "2025-07-08",
    "fimVigencia": "2027-07-09",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 5064959.1,
    "valorAtualizado": 5064959.1,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "José",
    "fiscalContrato": "Leandro",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C132024",
    "statusContrato": "Encerrado",
    "numeroContrato": 13,
    "anoContrato": 2024,
    "processoSEI": "01.20.00089932/2024.22",
    "objeto": "Contratação de empresa especializada na área de engenharia/arquitetura para execução de obra de reforma de três salas no Edifício Atalaia, para uso da Maringá Previdência - Previdência dos Servidores Públicos Municipais de Maringá, no município de Maringá – PR. Serão executados serviços de demolição de pisos/revestimentos, divisórias e algumas paredes; retirada de louças e metais, suportes, rodapés e acabamentos; retirada e isolamento de pontos hidrossanitários e elétricos; manutenção de esquadrias existentes que compõem a fachada do prédio; impermeabilização de áreas molhadas; construção de paredes em drywall; revestimentos de piso e de parede; pintura; instalações em granito; instalações de louças, metais, elétrica, hidrossanitário, marcenaria e comunicação visual. O objeto deverá ser executado de acordo com os projetos e documentação relacionada, conforme documentos citados no item 9.3 - Anexos do Projeto Básico do Projeto Básico. A intervenção deverá ser entregue de acordo com os prazos e cronograma apresentados no item 3.3 - Prazo de entrega ou de execução do objeto e item 3.4 - Cronograma para execução do Projeto Básico.",
    "categoriaContrato": "Obras",
    "tipoContratacao": "Concorrência ",
    "numeroLicitacao": "2/2024",
    "fornecedor": "CONSTRUTORA PLANESPACO LTDA",
    "cnpjFornecedor": "80.602.154/0001-92",
    "inicioVigencia": "2024-10-30",
    "fimVigencia": "2025-07-26",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 327998.87,
    "valorAtualizado": 327998.87,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "INCC",
    "gestorContrato": "Leandro",
    "fiscalContrato": "Rodrigo",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": false
  },
  {
    "idContrato": "C042024",
    "statusContrato": "Ativo",
    "numeroContrato": 4,
    "anoContrato": 2024,
    "processoSEI": "03.31.00000077/2024.12",
    "objeto": "Processo de Inexigibilidade de Licitação, visando o pagamento de despesas decorrentes do consumo de energia elétrica da Maringá Previdência à Companhia Paranaense de Energia – COPEL, em virtude da exclusividade no fornecimento, conforme Quinto Termo Aditivo ao Contrato de Concessão de Serviço Público de Distribuição de Energia Elétrica n° 46/1999-ANEEL no documento SEI n° 3262787",
    "categoriaContrato": "Energia Elétrica",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "4/2024",
    "fornecedor": "COPEL DISTRIBUICAO S.A",
    "cnpjFornecedor": "04.368.898/0001-06",
    "inicioVigencia": "2024-03-18",
    "fimVigencia": "2041-04-20",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 70000.0,
    "valorAtualizado": 169166.66,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C102024",
    "statusContrato": "Encerrado",
    "numeroContrato": 10,
    "anoContrato": 2024,
    "processoSEI": "03.31.00000036/2024.52",
    "objeto": "Contratação de serviços de consultoria financeira de forma presencial por telefone, e-mail ou outro meio eletrônico, que visa proporcionar aos gestores a possibilidade de planejar, avaliar e gerenciar os investimentos dos recursos financeiros do regime de previdência de forma eficaz e objetiva, acompanhando a rentabilidade mensal da carteira, os riscos envolvidos em cada fundo de investimento, o enquadramento legal, além de todos os elementos necessários ao cumprimento das obrigações estipuladas nas normas e legislações vigentes.",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Concorrência ",
    "numeroLicitacao": "1/2024",
    "fornecedor": "CRÉDITO & MERCADO GESTÃO DE VALORES MOBILIÁRIOS LTDA",
    "cnpjFornecedor": "11.340.009/0001-68",
    "inicioVigencia": "2024-06-11",
    "fimVigencia": "2025-06-10",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 7200.0,
    "valorAtualizado": 7200.0,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 600.0,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Leandro",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C052022",
    "statusContrato": "Encerrado",
    "numeroContrato": 5,
    "anoContrato": 2022,
    "processoSEI": "03.31.00000125/2022.80",
    "objeto": " Prestação de serviços de limpeza e polimento dos veículos oficiais da Maringá Previdência.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "6/2022",
    "fornecedor": "D.C.R. GOMES SOLUCOES E SERVICOS",
    "cnpjFornecedor": "35.968.162/0001-00",
    "inicioVigencia": "2022-09-12",
    "fimVigencia": "2023-08-11",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 2640.0,
    "valorAtualizado": 2640.0,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Cinthia",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": false
  },
  {
    "idContrato": "C102023",
    "statusContrato": "Encerrado",
    "numeroContrato": 10,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000727/2023.22",
    "objeto": "Prestação de serviços de limpeza e polimento dos veículos oficiais da Maringá Previdência. ",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "13/2023",
    "fornecedor": "D.C.R. GOMES SOLUCOES E SERVICOS",
    "cnpjFornecedor": "35.968.162/0001-00",
    "inicioVigencia": "2023-10-09",
    "fimVigencia": "2024-10-08",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 4560.0,
    "valorAtualizado": 4560.0,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Carlos",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": false
  },
  {
    "idContrato": "C112024",
    "statusContrato": "Ativo",
    "numeroContrato": 11,
    "anoContrato": 2024,
    "processoSEI": "01.35.00086439/2023.33",
    "objeto": "Contratação de empresa especializada para aquisição de licença de uso de software, implantação, conversão de dados, instalação e integração com outros sistemas utilizados, suporte técnico e manutenção, treinamento, hora técnica de customização e provimento de Datacenter destinado ao SISTEMA DE APOIO A GESTÃO PÚBLICA",
    "categoriaContrato": "Software",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "278/2023",
    "fornecedor": "ELOTECH GESTAO PUBLICA LTDA.",
    "cnpjFornecedor": "80.896.194/0001-64",
    "inicioVigencia": "2024-07-10",
    "fimVigencia": "2027-08-09",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 679760.0,
    "valorAtualizado": 679760.0,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 15840.0,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA ou INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C132021",
    "statusContrato": "Ativo",
    "numeroContrato": 13,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Prestação de serviços estratégicos de solução de tecnologia da informação (TI) pela DATAPREV à CONTRATANTE, conforme especificações técnicas descritas no Anexo I (Modelo de Negócio), visando atender os objetivos estratégicos da CONTRATANTE.",
    "categoriaContrato": "Software",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "4/2021",
    "fornecedor": "EMPRESA DE TECNOLOGIA E INFORMAÇÕES DA PREVIDENCIA - DATAPREV S.A",
    "cnpjFornecedor": "42.422.253/0001-01",
    "inicioVigencia": "2022-01-01",
    "fimVigencia": "2026-12-31",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 168000.0,
    "valorAtualizado": 168000.0,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 2800.0,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Maria Silvana",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C152024",
    "statusContrato": "Ativo",
    "numeroContrato": 15,
    "anoContrato": 2024,
    "processoSEI": "03.31.00001294/2024.36",
    "objeto": "Contratação de serviços estratégicos de solução de tecnologia da informação (TI), de solução única, padronizada e multiclientes, para fornecimento do serviço de Batimento de Dados do Sistema de Informações do Registro Civil – SIRC, plataforma digital que conecta os cartórios aos ambientes de governo eletrônico do Estado Brasileiro.",
    "categoriaContrato": "Software",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "9/2024",
    "fornecedor": "EMPRESA DE TECNOLOGIA E INFORMAÇÕES DA PREVIDENCIA - DATAPREV S.A",
    "cnpjFornecedor": "42.422.253/0001-01",
    "inicioVigencia": "2024-11-04",
    "fimVigencia": "2029-10-30",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 224024.4,
    "valorAtualizado": 224024.4,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "ICTI",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C032021",
    "statusContrato": "Encerrado",
    "numeroContrato": 3,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Contratação de empresa especializada na área de engenharia/arquitetura para a execução de obra de reforma e adequação de acessibilidade da sede da Maringá Previdência.",
    "categoriaContrato": "Obras",
    "tipoContratacao": "Tomada de preços",
    "numeroLicitacao": "1/2020",
    "fornecedor": "FAMA ENGENHARIA EIRELI",
    "cnpjFornecedor": "28.740.989/0001-99",
    "inicioVigencia": "2021-05-05",
    "fimVigencia": "2022-03-01",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 892598.55,
    "valorAtualizado": 892598.55,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Rodrigo",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": true
  },
  {
    "idContrato": "C032023",
    "statusContrato": "Encerrado",
    "numeroContrato": 3,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000245/2022.41",
    "objeto": "Contratação de pessoa jurídica para verificação de dados do Censo Previdenciário on-line a fim de atualizar, complementar, validar e armazenar os dados cadastrais e funcionais e de tempos anteriores, dos segurados da Maringá Previdência, exclusivamente, referente aos servidores efetivos ativos, aposentados e pensionistas, inclusive seus dependentes.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "3/2023",
    "fornecedor": "FUNDAÇÃO DE APOIO AO DESENVOLVIMENTO DA UNIVERSIDADE ESTADUAL DO CENTRO-OESTE",
    "cnpjFornecedor": "03.757.610/0001-22",
    "inicioVigencia": "2023-02-07",
    "fimVigencia": "2023-08-07",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 347365.37,
    "valorAtualizado": 347365.37,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": false
  },
  {
    "idContrato": "C062025",
    "statusContrato": "Ativo",
    "numeroContrato": 6,
    "anoContrato": 2025,
    "processoSEI": "03.31.00000700/2025.66",
    "objeto": "Contratação de pessoa jurídica especializada na prestação de serviços técnicos para a realização de estudo de viabilização e modernização atuarial e financeira da Maringá Previdência - Previdência dos Servidores Públicos Municipais de Maringá.",
    "categoriaContrato": "Atuarial",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "10/2025",
    "fornecedor": "FUNDACAO INSTITUTO DE PESQUISAS ECONOMICAS – FIPE",
    "cnpjFornecedor": "43.942.358/0001-46",
    "inicioVigencia": "2025-07-25",
    "fimVigencia": "2026-12-31",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 1365760.0,
    "valorAtualizado": 1365760.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Edimar",
    "fiscalContrato": "José",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": false
  },
  {
    "idContrato": "C112021",
    "statusContrato": "Encerrado",
    "numeroContrato": 11,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Contratação de empresa para a prestação de serviços de assistência à saúde para a quantidade estimada de 36.000 (trinta e seis mil) vidas, que incluem servidores públicos efetivos ativos e inativos, empregados públicos, seus dependentes e pensionistas para atendimento das necessidades das Secretarias e Órgãos vinculados ao Município de Maringá, por solicitação da Secretaria Municipal de Gestão de Pessoas – Diretoria de Saúde Ocupacional.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "306/2021",
    "fornecedor": "HOSPITAL BOM SAMARITANO DE MARINGA S/A",
    "cnpjFornecedor": "23.876.304/0001-12",
    "inicioVigencia": "2021-11-27",
    "fimVigencia": "2026-01-31",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 5308707.6,
    "valorAtualizado": 29308047.48,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C042023",
    "statusContrato": "Encerrado",
    "numeroContrato": 4,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000090/2023.52",
    "objeto": "Contratação de prestação de serviço de entidade certificadora para verificação do cumprimento dos requisitos estabelecidos no Programa de Certificação Institucional e Modernização da Gestão dos Regimes Próprios de Previdência Social da União, dos Estados, do Distrito Federal e dos Municípios – Pró-Gestão RPPS, notadamente quanto aos critérios estabelecidos no Nível II, que visa a adoção de práticas de gestão previdenciária relativas a controles internos, governança corporativa e educação previdenciária.",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "4/2023",
    "fornecedor": "ICQ-ATZERT LTDA",
    "cnpjFornecedor": "01.659.386/0001-00",
    "inicioVigencia": "2023-02-13",
    "fimVigencia": "2026-03-12",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 7400.0,
    "valorAtualizado": 7400.0,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C082025",
    "statusContrato": "Ativo",
    "numeroContrato": 8,
    "anoContrato": 2025,
    "processoSEI": "03.31.00001216/2025.05",
    "objeto": "Contratação de prestação de serviço de entidade certificadora para verificação do cumprimento dos requisitos estabelecidos no Programa de Certificação Institucional e Modernização da Gestão dos Regimes Próprios de Previdência Social da União, dos Estados, do Distrito Federal e dos Municípios – Pró-Gestão RPPS, notadamente quanto aos critérios estabelecidos no Nível II, que visa a adoção de práticas de gestão previdenciária relativas a controles internos, governança corporativa e educação previdenciária.",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "16/2025",
    "fornecedor": "ICQ-ATZERT LTDA",
    "cnpjFornecedor": "01.659.386/0001-00",
    "inicioVigencia": "2025-11-19",
    "fimVigencia": "2028-11-19",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 8950.0,
    "valorAtualizado": 8950.0,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "José",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C012023",
    "statusContrato": "Ativo",
    "numeroContrato": 1,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000281/2022.39",
    "objeto": "Contratação de empresa especializada na área de tecnologia da informação para prestação de serviços de desenvolvimento, suporte e hospedagem de site e e-mail para a Maringá Previdência.",
    "categoriaContrato": "Software",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "9/2022",
    "fornecedor": "INGA INFORMATICA E COMUNICAÇÃO",
    "cnpjFornecedor": "07.565.202/001-20",
    "inicioVigencia": "2023-01-06",
    "fimVigencia": "2027-01-05",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 7200.0,
    "valorAtualizado": 30533.88,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 560.78,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C092023",
    "statusContrato": "Encerrado",
    "numeroContrato": 9,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000722/2023.60",
    "objeto": "Contratação de empresa especializada para prestação de serviço de central telefônica IP em nuvem, locação de aparelhos telefônicos IP, incluindo o serviço de manutenção, implantação, suporte e com todas as necessidades relacionadas, visando a substituição do sistema de telefonia atualmente utilizado, com vistas a sua modernização, integração, otimização de gestão, aumento da segurança e disponibilidade de acesso, virtualizando ao máximo possível as funções lógicas de PABX, em consonância aos parâmetros, bem como as normatizações da Agência Nacional de Telecomunicações (ANATEL) e conforme especificações descritas neste termo, para a Maringá Previdência.",
    "categoriaContrato": "Comunicação",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "12/2023",
    "fornecedor": "JJPG COMERCIO E SERVIÇOS DE INFORMATICA LTDA - ME",
    "cnpjFornecedor": "08.495.432/0001-22",
    "inicioVigencia": "2023-09-25",
    "fimVigencia": "2025-08-24",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 17460.0,
    "valorAtualizado": 34883.76,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Carlos",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C072025",
    "statusContrato": "Ativo",
    "numeroContrato": 7,
    "anoContrato": 2025,
    "processoSEI": "03.31.00000792/2025.07",
    "objeto": "Contratação de empresa na prestação do serviço comum de telefonia corporativa, com central telefônica com a tecnologia de voz sobre IP (VoIP), incluindo-se a interconexão com a rede de telefonia pública comutada (PSTN), de modo a prover a fruição do Serviço Telefônico Fixo Comutado – STFC (fixo-fixo e fixo-móvel), nas modalidades Local e Longa Distância Nacional (LDN) e Longa Distância Internacional (LDI).",
    "categoriaContrato": "Comunicação",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "11/2025",
    "fornecedor": "JJPG COMERCIO E SERVIÇOS DE INFORMATICA LTDA – ME",
    "cnpjFornecedor": "08.495.432/0001-22",
    "inicioVigencia": "2025-09-01",
    "fimVigencia": "2027-08-31",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 49020.0,
    "valorAtualizado": 98040.0,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "José",
    "fiscalContrato": "Gustavo",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C042022",
    "statusContrato": "Encerrado",
    "numeroContrato": 4,
    "anoContrato": 2022,
    "processoSEI": "03.31.00000121/2022.91",
    "objeto": "Contratação de pessoa jurídica para prestação de acesso à internet banda larga de fibra ótica com velocidade de 500 MBps com um ponto de roteador wi-fi.",
    "categoriaContrato": "Comunicação",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "6/2022",
    "fornecedor": "LIGGA TELECOMUNICAÇÕES S.A",
    "cnpjFornecedor": "04.368.865/0001-66",
    "inicioVigencia": "2022-09-19",
    "fimVigencia": "2023-09-18",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 3598.8,
    "valorAtualizado": 3598.8,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 299.9,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C062021",
    "statusContrato": "Encerrado",
    "numeroContrato": 6,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Contratação de pessoa jurídica para prestação de acesso à internet banda larga de fibra ótica com velocidade de 500 MBps com um ponto de roteador wi-fi",
    "categoriaContrato": "Comunicação",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "4/2021",
    "fornecedor": "LIGGA TELECOMUNICAÇÕES S.A",
    "cnpjFornecedor": "04.368.865/0001-66",
    "inicioVigencia": "2021-08-16",
    "fimVigencia": "2022-08-15",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 3698.8,
    "valorAtualizado": 3698.8,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 299.9,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Elisangela",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C062023",
    "statusContrato": "Encerrado",
    "numeroContrato": 6,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000330/2023.71",
    "objeto": "Contratação de empresa especializada na locação de espaço, com serviços de Buffet (coffee break), para realização do 2º Seminário Previdenciário que será promovido aos segurados da Maringá Previdência.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "9/2023",
    "fornecedor": "LUXTOUR HOTELARIA, EVENTOS E TURISMO LTDA",
    "cnpjFornecedor": "07.057.670/0001-93",
    "inicioVigencia": "2023-06-28",
    "fimVigencia": "2023-12-30",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 16987.5,
    "valorAtualizado": 16987.5,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Alessandra",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C062022",
    "statusContrato": "Encerrado",
    "numeroContrato": 6,
    "anoContrato": 2022,
    "processoSEI": "03.31.00000164/2022.94",
    "objeto": "Contratação de empresa especializada na locação de espaço, com serviços de Buffet (coffee break), para realização de Seminário Previdenciário que será promovido aos segurados da Maringá Previdência.",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "7/2022",
    "fornecedor": "LUXTOUR HOTELARIA, EVENTOS E TURISMO LTDA ",
    "cnpjFornecedor": "07.057.670/001-93",
    "inicioVigencia": "2022-09-28",
    "fimVigencia": "2022-12-26",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 10870.5,
    "valorAtualizado": 10870.5,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Alessandra",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C092024",
    "statusContrato": "Encerrado",
    "numeroContrato": 9,
    "anoContrato": 2024,
    "processoSEI": "03.31.00000007/2024.59",
    "objeto": "Contratação de empresa especializada para confecção, montagem e instalação de móveis para Maringá Previdência.",
    "categoriaContrato": "Materiais Permanentes",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "1/2024",
    "fornecedor": "M DO C M OLIVEIRA MOVEIS",
    "cnpjFornecedor": "03.042.841/0001-50",
    "inicioVigencia": "2024-05-09",
    "fimVigencia": "2025-05-08",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 144355.5,
    "valorAtualizado": 144355.5,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C122024",
    "statusContrato": "Ativo",
    "numeroContrato": 12,
    "anoContrato": 2024,
    "processoSEI": "03.31.00000424/2024.52",
    "objeto": "Contratação de empresa especializada para proporcionar cobertura securitária automotiva dos veículos oficiais da Maringá Previdência: I - Nissan Sentra 2.0S CVT, ano 2018/2019, placa BCF-3568; II - Volkswagen Voyage 1.6 Comfortline, ano 2009/2010, placa ARW-0165.",
    "categoriaContrato": "Seguro",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "5/2024",
    "fornecedor": "MAPFRE SEGUROS GERAIS S.A.",
    "cnpjFornecedor": "61.074.175/0001-38",
    "inicioVigencia": "2024-08-05",
    "fimVigencia": "2027-08-04",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 2439.29,
    "valorAtualizado": 5053.89,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "IPCA",
    "gestorContrato": "José",
    "fiscalContrato": "Gustavo",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": true
  },
  {
    "idContrato": "C022025",
    "statusContrato": "Encerrado",
    "numeroContrato": 2,
    "anoContrato": 2025,
    "processoSEI": "03.31.00001244/2024.28",
    "objeto": "Contratação de prestação de serviços de lavagem e polimento dos veículos oficiais pertencentes a frota da Autarquia",
    "categoriaContrato": "Serviços",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "1/2025",
    "fornecedor": "MATHEUS PEDRIALI MUSSIO",
    "cnpjFornecedor": "57.604.284/0001-66",
    "inicioVigencia": "2025-03-07",
    "fimVigencia": "2026-03-06",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": true,
    "valorInicialContrato": 3912.0,
    "valorAtualizado": 3912.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "José",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": false
  },
  {
    "idContrato": "C042025",
    "statusContrato": "Ativo",
    "numeroContrato": 4,
    "anoContrato": 2025,
    "processoSEI": "03.31.00000600/2025.50",
    "objeto": "Contratação de serviços de consultoria financeira de forma presencial, por telefone, e-mail ou outro meio eletrônico, que visa proporcionar aos gestores a possibilidade de planejar, avaliar e gerenciar os investimentos dos recursos financeiros do regime de previdência de forma eficaz e objetiva, acompanhando a rentabilidade mensal da carteira, os riscos envolvidos em cada investimento, o enquadramento legal, além de todos os elementos necessários ao cumprimento das obrigações estipuladas nas normas e legislações vigentes.",
    "categoriaContrato": "Consultoria",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "5/2025",
    "fornecedor": "MATIAS E LEITAO CONSULTORES ASSOCIADOS LTDA.",
    "cnpjFornecedor": "14.813.501/0001-00",
    "inicioVigencia": "2025-06-11",
    "fimVigencia": "2027-06-11",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 75600.0,
    "valorAtualizado": 154306.92,
    "recorrenciaContratual": "Mensal",
    "valorMensal": 6558.91,
    "possuiReajuste": true,
    "indiceReajuste": "INPC",
    "gestorContrato": "José",
    "fiscalContrato": "Leandro",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C052023",
    "statusContrato": "Encerrado",
    "numeroContrato": 5,
    "anoContrato": 2023,
    "processoSEI": null,
    "objeto": "Contratação de empresa especializada na área de engenharia e arquitetura para elaboração de projetos técnicos para reforma interna das salas comerciais do Edifício Atalaia.",
    "categoriaContrato": "Obras",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "5/2023",
    "fornecedor": "MORAN PROJETOS E MONTAGENS ELETRICAS LTDA.",
    "cnpjFornecedor": "00.906.796/0001-46",
    "inicioVigencia": "2023-03-31",
    "fimVigencia": "2024-11-05",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 32980.0,
    "valorAtualizado": 32980.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Rodrigo",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": false
  },
  {
    "idContrato": "C022022",
    "statusContrato": "Encerrado",
    "numeroContrato": 2,
    "anoContrato": 2022,
    "processoSEI": "03.31.00000095/2022.17",
    "objeto": "Contratação de empresa especializada para administrar o fornecimento, gerenciamento e controle de combustíveis dos dois veículos da Maringá Previdência, em que os abastecimentos serão prestados por postos credenciados, por meio da implantação e operação de um sistema informatizado e integrado com a utilização de cartão de pagamento magnético e disponibilização de Rede Credenciada de Postos de Combustível, compreendendo a distribuição de etanol e gasolina comum, para veículos automotores e equipamentos pertencentes a autarquia, ou que venham a fazer parte desta, nos termos da legislação vigente.",
    "categoriaContrato": "Combustivel",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "2/2022",
    "fornecedor": "PERSONAL NET TECNOLOGIA DE INFORMAÇÃO LTDA",
    "cnpjFornecedor": "09.687.900/0002-04",
    "inicioVigencia": "2022-07-20",
    "fimVigencia": "2023-07-19",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 16800.0,
    "valorAtualizado": 16800.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Carlos",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C072023",
    "statusContrato": "Ativo",
    "numeroContrato": 7,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000590/2023.35",
    "objeto": "Contratação de empresa especializada para administrar o fornecimento, gerenciamento e controle de combustíveis dos dois veículos da Maringá Previdência, em que os abastecimentos serão prestados por postos credenciados, por meio da implantação e operação de um sistema informatizado e integrado com a utilização de cartão de pagamento magnético e disponibilização de Rede Credenciada de Postos de Combustível, compreendendo a distribuição de etanol e gasolina comum, para veículos automotores e equipamentos pertencentes a autarquia, ou que venham a fazer parte desta, nos termos da legislação vigente.",
    "categoriaContrato": "Combustivel",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "11/2023",
    "fornecedor": "PERSONAL NET TECNOLOGIA DE INFORMAÇÃO LTDA",
    "cnpjFornecedor": "09.687.900/0002-04",
    "inicioVigencia": "2023-08-02",
    "fimVigencia": "2027-08-01",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 16800.0,
    "valorAtualizado": 67200.0,
    "recorrenciaContratual": "sobDemanda",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "José",
    "fiscalContrato": "Gustavo",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C082021",
    "statusContrato": "Encerrado",
    "numeroContrato": 8,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Contratação de empresa especializada para o fornecimento e entrega, na sede da Maringá Previdência, de materiais e equipamentos de processamento de dados, visando o atendimento dos setores administrativos, financeiro e de benefícios.",
    "categoriaContrato": "Materiais Permanentes",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "5/2021",
    "fornecedor": "R P MACHADO INFORMATICA",
    "cnpjFornecedor": "06.035.393/0001-55",
    "inicioVigencia": "2021-08-19",
    "fimVigencia": "2022-08-18",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 28054.0,
    "valorAtualizado": 28054.0,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Carlos",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C142024",
    "statusContrato": "Encerrado",
    "numeroContrato": 14,
    "anoContrato": 2024,
    "processoSEI": "03.31.00001260/2024.81",
    "objeto": "Contratação de prestação de serviço de Sistema de Gerenciamento Automatizado para sala de reuniões e auditório da Maringá Previdência, incluindo: 1- Sistema de software para gerenciamento das gravações e transmissões; 2- Sonorização, captação de áudio e vídeo, incluindo transmissão online; 3- Fornecimento de todos os equipamentos e softwares necessários a implantação; 4- Treinamento dos servidores e Conselheiros quanto ao uso do sistema e equipamentos.",
    "categoriaContrato": "Materiais Permanentes",
    "tipoContratacao": "Pregão",
    "numeroLicitacao": "2/2024",
    "fornecedor": "RIOLE - ELETRÔNICA LTDA",
    "cnpjFornecedor": "76.617.927/0001-37",
    "inicioVigencia": "2024-11-04",
    "fimVigencia": "2025-05-03",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 305000.0,
    "valorAtualizado": 305000.0,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C072021",
    "statusContrato": "Encerrado",
    "numeroContrato": 7,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Contratação de empresa especializada para o fornecimento e entrega, na sede da Maringá Previdência, de materiais e equipamentos de processamento de dados, visando o atendimento dos setores administrativos, financeiro e de benefícios.",
    "categoriaContrato": "Materiais Permanentes",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "5/2021",
    "fornecedor": "SYMA COMPUTADORES LTDA",
    "cnpjFornecedor": "04.912.543/0001-02",
    "inicioVigencia": "2021-08-19",
    "fimVigencia": "2022-08-18",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 10379.21,
    "valorAtualizado": 10379.21,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Carlos",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C012024",
    "statusContrato": "Ativo",
    "numeroContrato": 1,
    "anoContrato": 2024,
    "processoSEI": "03.31.00000079/2024.55",
    "objeto": "Aquisição de vale-transporte para os servidores da Maringá Previdência.",
    "categoriaContrato": "Vale-transporte",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "2/2024",
    "fornecedor": "TRANSPORTE COLETIVO CIDADE CANCAO LTDA",
    "cnpjFornecedor": "79.118.311/0001-00",
    "inicioVigencia": "2024-02-11",
    "fimVigencia": "2030-02-11",
    "possibilidadeProrrogacao": true,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 49923.11,
    "valorAtualizado": 99846.23,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": true,
    "indiceReajuste": "Outro",
    "gestorContrato": "Maria Silvana",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C022023",
    "statusContrato": "Encerrado",
    "numeroContrato": 2,
    "anoContrato": 2023,
    "processoSEI": "03.31.00000023/2023.18",
    "objeto": "Aquisição de vale-transporte para os servidores da Maringá Previdência.",
    "categoriaContrato": "Vale-transporte",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "1/2023",
    "fornecedor": "TRANSPORTE COLETIVO CIDADE CANCAO LTDA",
    "cnpjFornecedor": "07.057.670/0001-00",
    "inicioVigencia": "2023-02-11",
    "fimVigencia": "2024-02-10",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 27363.81,
    "valorAtualizado": 27363.81,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Elisangela",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C012021",
    "statusContrato": "Encerrado",
    "numeroContrato": 1,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "Aquisição de vale-transporte para os servidores da Maringá Previdência.",
    "categoriaContrato": "Vale-transporte",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "1/2021",
    "fornecedor": "TRANSPORTE COLETIVO CIDADE CANCAO LTDA",
    "cnpjFornecedor": "79.118.311/0001-00",
    "inicioVigencia": "2021-02-11",
    "fimVigencia": "2022-02-10",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 43136.12,
    "valorAtualizado": 43136.12,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Cinthia",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C012022",
    "statusContrato": "Encerrado",
    "numeroContrato": 1,
    "anoContrato": 2022,
    "processoSEI": null,
    "objeto": "Aquisição de vale-transporte para os servidores da Maringá Previdência.",
    "categoriaContrato": "Vale-transporte",
    "tipoContratacao": "Inexigibilidade",
    "numeroLicitacao": "1/2022",
    "fornecedor": "TRANSPORTE COLETIVO CIDADE CANCAO LTDA",
    "cnpjFornecedor": "79.118.311/0001-00",
    "inicioVigencia": "2022-02-11",
    "fimVigencia": "2023-02-10",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 51292.58,
    "valorAtualizado": 51292.58,
    "recorrenciaContratual": "mensalEstimado",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Cinthia",
    "fiscalContrato": "Elisangela",
    "riscoDescontinuidade": "Alto",
    "servicoEssencial": true
  },
  {
    "idContrato": "C032025",
    "statusContrato": "Encerrado",
    "numeroContrato": 3,
    "anoContrato": 2025,
    "processoSEI": "03.31.00000299/2025.29",
    "objeto": "Aquisição placas de gesso, porta e serviço de instalação e pintura para construção de uma parede a fim de dividir a sala de arquivo em duas salas, sendo uma de trabalho e uma de arquivo de documentos.",
    "categoriaContrato": "Obras",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "4/2025",
    "fornecedor": "UPTECH CONSTRUTORA LTDA",
    "cnpjFornecedor": "57.658.586/0001-01",
    "inicioVigencia": "2025-04-28",
    "fimVigencia": "2025-06-27",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 3008.0,
    "valorAtualizado": 3008.0,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "José",
    "fiscalContrato": "Edno",
    "riscoDescontinuidade": "Baixo",
    "servicoEssencial": false
  },
  {
    "idContrato": "C092021",
    "statusContrato": "Encerrado",
    "numeroContrato": 9,
    "anoContrato": 2021,
    "processoSEI": null,
    "objeto": "A contratação se motiva diante da necessidade de adequar a infraestrutura física às necessidades funcionais dos servidores, que devido ao tempo de uso está deteriorada, bem como dar acessibilidade aos mais de 3 mil beneficiários da entidade.",
    "categoriaContrato": "Obras",
    "tipoContratacao": "Dispensa",
    "numeroLicitacao": "6/2021",
    "fornecedor": "ZERONOVE ARQUITETURA LTDA ME",
    "cnpjFornecedor": "11.704.375/0001-59",
    "inicioVigencia": "2021-10-18",
    "fimVigencia": "2022-03-17",
    "possibilidadeProrrogacao": false,
    "necessitaNovaContratacao": false,
    "valorInicialContrato": 6175.61,
    "valorAtualizado": 6175.61,
    "recorrenciaContratual": "única",
    "valorMensal": null,
    "possuiReajuste": false,
    "indiceReajuste": null,
    "gestorContrato": "Leandro",
    "fiscalContrato": "Rodrigo",
    "riscoDescontinuidade": "Médio",
    "servicoEssencial": true
  }
];

export const rawContratosData = contratosData;
